<a href="https://colab.research.google.com/github/AnandJL/Assesment2/blob/main/Assessment2_Anand_JL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. NumPy Array Creation

Create a NumPy array containing the following values:

10, 20, 30, 40, 50

Display:

The array

Shape of the array

Data type of the array

In [ ]:
import numpy as np

ar = np.array([10,20,30,40,50])
print("Array :",ar)
print("Shape :",ar.shape)
print("Data type :",ar.dtype)

Array : [10 20 30 40 50]
Shape : (5,)
Data type : int64

Q2. NumPy Array Operations

Given:

import numpy as np

arr = np.array([5, 10, 15, 20, 25])

Using NumPy:

Add 5 to every element.

Multiply every element by 2.

Display the results.

In [ ]:
import numpy as np
arr = np.array([5,10,15,20,25])

new_add = arr + 5
new_mul = arr * 2

print("Add :",new_add)
print("Multiply :",new_mul)

Add : [10 15 20 25 30]
Multiply : [10 20 30 40 50]

Q3. NumPy Statistical Operations

Given:

arr = np.array([12, 15, 18, 20, 25, 30])

Using NumPy, calculate:

Mean

Median

Minimum

Maximum

Standard deviation

In [ ]:
import numpy as np
from statistics import mean,median,stdev
arr2 = np.array([12,15,18,20,25,30])

print("Mean: ",mean(arr2))
print("Median: ",median(arr2))
print("Minimum: ",min(arr2))
print("Maximum: ",max(arr2))
print("Standard Deviation: ",np.std(arr2))

Mean:  20
Median:  19.0
Minimum:  12
Maximum:  30
Standard Deviation:  6.027713773341708

Q4. NumPy Filtering

Given:

arr = np.array([10, 25, 30, 45, 50, 65, 70])

Using NumPy, extract all values that are greater than 40.

In [ ]:
import numpy as np
arr3 = np.array([10,25,30,45,50,65,70])
print("Values greater than 40: ",arr3[arr3>40])

Values greater than 40:  [45 50 65 70]

Q5. Create a Pandas DataFrame

Create the following DataFrame using Pandas:

Name Age Score

Anu   21    85

Rahul 22    72

Meera 20    91

Arun 23     68

Display the DataFrame

In [ ]:
import pandas as pd

df = pd.DataFrame({'Name':['Anu','Rahul','Meera','Arun'],'Age':[21,22,20,23],'Score':[85,72,91,68]})
df

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

Q6. DataFrame Selection

Using the DataFrame created in Q5:

Display only the Name and Score columns.

Display the complete record of Meera .

In [ ]:
print(df[['Name','Score']])
print("\nComplete record of Meera \n",df[df['Name']=='Meera'])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

Complete record of Meera
     Name  Age  Score
2  Meera   20     91

Q7. DataFrame Filtering

Using the DataFrame from Q5, display all students whose Score is greater than 75.

In [ ]:
print(df[df['Score']>75])

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

Q8. DataFrame Inspection

Using the DataFrame from Q5, display:

1. Number of rows and columns

2. Column names

3. Data types

4. Basic statistical summary

In [ ]:
print("No. of rows: ",df.shape[0])
print("\nNo. of columns: ",df.shape[1])
print("\nColumn names: ",df.columns)
print("\nData types: \n",df.dtypes)
print("\nBasic statistical summary: \n",df.describe)

No. of rows:  4

No. of columns:  3

Column names:  Index(['Name', 'Age', 'Score'], dtype='object')

Data types:
 Name     object
Age       int64
Score     int64
dtype: object

Basic statistical summary:
 <bound method NDFrame.describe of     Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68>

Q9. Sorting a DataFrame

Sort the DataFrame from Q5 by Score in descending order.

In [ ]:
print("Descending order: ",df.sort_values(by='Score',ascending=False))

Descending order:      Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

Q10. Handling Missing Values

Consider the following DataFrame:

df = pd.DataFrame({

'Name': ['A', 'B', 'C', 'D'],

'Age': [21, np.nan, 23, 22],

'Score': [80, 75, np.nan, 90]

})
Write Pandas code to:

1.Identify the missing values.

2.Replace the missing Age with the mean age.

3.Replace the missing Score with the mean score.

In [ ]:
df1 = pd.DataFrame({'Name':['A','B','C','D'],'Age':[21,np.nan,23,22],'Score':[80,75,np.nan,90]})
print("Missing values: \n",df1.isnull)
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Score'] = df['Score'].fillna(df['Score'].mean())

Missing values:
 <bound method DataFrame.isnull of   Name   Age  Score
0    A  21.0   80.0
1    B   NaN   75.0
2    C  23.0    NaN
3    D  22.0   90.0>

Q11. Data Loading and Exploration

Load student_performance.csv into a Pandas DataFrame.

Perform the following:

Display the first 5 records.

Display the last 5 records.

Find the number of rows and columns.

Display the column names.

Display the data types.

Generate a statistical summary of the numerical columns.

In [ ]:
import pandas as pd
student = pd.read_csv("/content/drive/MyDrive/DSA/Assessment 2/student_performance.csv")

print("First 5 records:\n",student.head())
print("\nLast 5 records: \n",student.tail())
print("\nNo. of rows: ",student.shape[0])
print("\nNo. of columns: ",student.shape[1])
print("\nColumn names: ",student.columns)
print("\nData types: \n",student.dtypes)

First 5 records:
   Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0          89.4       86.3          81.9         76.7         82.7
1          70.3       63.1          65.1         62.3         60.3
2          79.9       80.4          65.3         68.0         67.1
3          65.8       50.7          52.6         48.8         57.2
4          90.1       82.9          72.4         87.7         81.9

Last 5 records:
    Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

No. of rows:  80

No. of columns:  11

Column names:  Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

Data types:
 Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

Q12. Filtering and Sorting

Using the student dataset:

Find students whose Final_Score is greater than 75.

Find students whose Attendance is below 75%.

Find students from the Data Science department with Final_Score greater than 80.

Sort all students by Final_Score from highest to lowest

In [ ]:
print("Students with Final_Score > 75:\n ",student[['Name','Final_Score']][student['Final_Score']>75])
print("\nStudents with Attendance < 75:\n ",student['Name'][student['Attendance']<75])
print("\nStudents from Data Science with Final_Score > 80:\n ",student[['Name','Department','Final_Score']][(student['Department']=='Data Science') & (student['Final_Score']>80)])
print("\nStudents sorted by Final_Score: \n",student.sort_values(by='Final_Score',ascending=False))

Students with Final_Score > 75:
                Name  Final_Score
0      Rahul Varma         82.7
4        Asha Nair         81.9
6      Akhil Varma         77.0
7      Akhil Varma         79.2
8       Diya Menon         83.0
10        Diya Das         91.9
11      Arun Reddy         86.9
16    Rahul Thomas         91.1
17      Priya Nair         75.1
23  Fathima Joseph         83.7
24     Kiran Varma         77.3
27     Nikhil Nair         77.1
30      Amal Varma         85.5
33        Amal Das         84.3
35      Maya Menon         84.2
37    Kiran Pillai         82.4
39    Rohan Sharma         78.5
40     Amal Pillai         94.5
41     Arun Joseph         77.9
43       Rahul Das         77.3
47     Priya Kumar         77.3
48     Asha Sharma         97.0
51      Gokul Nair         79.3
55     Vivek Varma         93.3
56    Rohan Pillai         75.2
57     Diya Thomas         92.3
58       Anu Menon         84.9
59      Asha Menon         87.9
61    Kiran Pillai         96.0
64    Rohan Sharma         83.5
67        Maya Das         83.7
73       Anu Kumar         83.4
77  Fathima Sharma         75.2
79      Diya Varma         78.6

Students with Attendance < 75:
  0        Rahul Varma
2     Fathima Joseph
4          Asha Nair
6        Akhil Varma
8         Diya Menon
9       Gokul Pillai
11        Arun Reddy
15      Nikhil Kumar
19      Vivek Sharma
25        Maya Menon
36      Nikhil Menon
42       Sneha Varma
43         Rahul Das
47       Priya Kumar
50       Gokul Menon
59        Asha Menon
64      Rohan Sharma
67          Maya Das
71      Vivek Pillai
Name: Name, dtype: object

Students from Data Science with Final_Score > 80:
              Name    Department  Final_Score
4      Asha Nair  Data Science         81.9
8     Diya Menon  Data Science         83.0
10      Diya Das  Data Science         91.9
16  Rahul Thomas  Data Science         91.1
48   Asha Sharma  Data Science         97.0
55   Vivek Varma  Data Science         93.3
59    Asha Menon  Data Science         87.9

Students sorted by Final_Score:
    Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

Q13. Feature Creation

Create a new column called:

Average_Technical_Score

Calculate it using:

Python_Score

SQL_Score

Pandas_Score

NumPy_Score

Then create another column called:

Performance

using these rules:

Average Technical Score   Performance

>= 90 Excellent

>= 75 Good

>= 60 Average

< 60 Needs Improvement

Display the resulting DataFrame.

In [ ]:
student['Average_Technical_Score'] = (student['Python_Score']+student['SQL_Score']+student['Pandas_Score']+student['NumPy_Score'])/4
student['Performance'] = np.where(student['Average_Technical_Score']>=90,'Excellent',np.where(student['Average_Technical_Score']>=75,'Good', np.where(student['Average_Technical_Score']>=60,'Average','Needs Improvement')))
student

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

Q14. GroupBy Analysis

Using the student dataset, calculate the following for each department:

Number of students

Average Final Score

Maximum Final Score

Minimum Final Score

Sort the resulting DataFrame by Average Final Score in descending order.

In [ ]:
print("No. of students by Department: ",student.groupby('Department')['Student_ID'].count())
print("\nAverage Final Score by Department: ",student.groupby('Department')['Final_Score'].mean())
print("\nMaximum Final Score by Department: ",student.groupby('Department')['Final_Score'].max())
print("\nMinimum Final Score by Department: ",student.groupby('Department')['Final_Score'].min())
print("\nSorted by Average Final Score: \n",student.groupby('Department')['Final_Score'].mean().sort_values(ascending=False))

No. of students by Department:  Department
 Data Science        1
Commerce             8
Computer Science    29
Computer science     1
Data Science        27
Electronics         13
data science         1
Name: Student_ID, dtype: int64

Average Final Score by Department:  Department
 Data Science       55.100000
Commerce            67.825000
Computer Science    71.479310
Computer science    46.700000
Data Science        71.324000
Electronics         72.846154
data science        66.900000
Name: Final_Score, dtype: float64

Maximum Final Score by Department:  Department
 Data Science       55.1
Commerce            83.7
Computer Science    96.0
Computer science    46.7
Data Science        97.0
Electronics         86.9
data science        66.9
Name: Final_Score, dtype: float64

Minimum Final Score by Department:  Department
 Data Science       55.1
Commerce            54.6
Computer Science    40.6
Computer science    46.7
Data Science        43.5
Electronics         51.2
data science        66.9
Name: Final_Score, dtype: float64

Sorted by Average Final Score:
 Department
Electronics         72.846154
Computer Science    71.479310
Data Science        71.324000
Commerce            67.825000
data science        66.900000
 Data Science       55.100000
Computer science    46.700000
Name: Final_Score, dtype: float64

Q15. NumPy and Pandas Integration

Using the student dataset:

Convert the Final_Score column into a NumPy array.

Calculate using NumPy:

1.Mean

2.Median

3.Standard deviation

4.25th percentile

5.75th percentile

Identify all students whose Final_Score is above the overall mean.

In [ ]:
stu=student['Final_Score']
np.array(stu)

print("Mean: ",np.mean(stu))
print("\nMedian: ",np.median(stu))
print("\nStandard Deviation: ",np.std(stu))
print("\n25th percentile: ",np.percentile(stu,25))
print("\n75th percentile: ",np.percentile(stu,75))
print("\nStudents with Final_Score > Mean: \n",student['Name'][student['Final_Score']>np.mean(stu)])

Mean:  70.69615384615385

Median:  nan

Standard Deviation:  13.963491245788179

25th percentile:  nan

75th percentile:  nan

Students with Final_Score > Mean:
 0        Rahul Varma
4          Asha Nair
6        Akhil Varma
7        Akhil Varma
8         Diya Menon
9       Gokul Pillai
10          Diya Das
11        Arun Reddy
16      Rahul Thomas
17        Priya Nair
20        Arun Varma
23    Fathima Joseph
24       Kiran Varma
27       Nikhil Nair
30        Amal Varma
33          Amal Das
35        Maya Menon
37      Kiran Pillai
39      Rohan Sharma
40       Amal Pillai
41       Arun Joseph
43         Rahul Das
46         Gokul Das
47       Priya Kumar
48       Asha Sharma
51        Gokul Nair
52        Maya Varma
55       Vivek Varma
56      Rohan Pillai
57       Diya Thomas
58         Anu Menon
59        Asha Menon
60    Fathima Sharma
61      Kiran Pillai
64      Rohan Sharma
66      Rahul Thomas
67          Maya Das
72     Swathi Joseph
73         Anu Kumar
74        Gokul Nair
77    Fathima Sharma
79        Diya Varma
Name: Name, dtype: object

Q16. Student Performance Analysis

In [ ]:
#  A. DATA CLEANING
#Identify missing values
import numpy as np
import pandas as pd
student = pd.read_csv("/content/drive/MyDrive/DSA/Assessment 2/student_performance.csv")

missing_val = student.isnull().sum()
print(missing_val)

student['Age'] = student['Age'].fillna(student['Age'].mean())
student['Attendance'] = student['Attendance'].fillna(student['Attendance'].mean())
student['Python_Score'] = student['Python_Score'].fillna(student['Python_Score'].mean())
student['SQL_Score'] = student['SQL_Score'].fillna(student['SQL_Score'].mean())
student['Pandas_Score'] = student['Pandas_Score'].fillna(student['Pandas_Score'].mean())
student['NumPy_Score'] = student['NumPy_Score'].fillna(student['NumPy_Score'].mean())
student['Final_Score'] = student['Final_Score'].fillna(student['Final_Score'].mean())

missing_val = student.isnull().sum()
print(missing_val)

# B. Feature Engineering

student['Average_Score'] = (student['Python_Score']+student['SQL_Score']+student['Pandas_Score']+student['NumPy_Score'])/4
student['Pass_Status'] = np.where(student['Average_Score']>=50,'Pass','Fail')

# C. Analysis

print("Top 5 students:",student.sort_values(by='Average_Score',ascending=False).head())
print('Department with highest avg score:',student.groupby('Department')['Average_Score'].head(1))
print("Average attendance by dept",student.groupby('Department')['Attendance'].mean())
print("No. of students who passed and failed",student.groupby('Pass_Status')['Student_ID'].count())


# D. Summary

print("Summary: \n",student.describe())

Student_ID      0
Name            0
Gender          0
Department      0
Age             3
Attendance      3
Python_Score    2
SQL_Score       0
Pandas_Score    2
NumPy_Score     2
Final_Score     2
dtype: int64
Student_ID      0
Name            0
Gender          0
Department      0
Age             0
Attendance      0
Python_Score    0
SQL_Score       0
Pandas_Score    0
NumPy_Score     0
Final_Score     0
dtype: int64
Top 5 students:    Student_ID          Name  Gender        Department   Age  Attendance  \
10    STU1011      Diya Das  Female      Data Science  20.0       100.0
61    STU1062  Kiran Pillai  Female  Computer Science  19.0        83.8
8     STU1009    Diya Menon    Male      Data Science  25.0        64.4
16    STU1017  Rahul Thomas  Female      Data Science  25.0        78.3
35    STU1036    Maya Menon  Female       Electronics  19.0        82.0

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
10         100.0       93.2         100.0         89.3         91.9
61         100.0      100.0          89.4         91.4         96.0
8           94.8       86.0          87.7        100.0         83.0
16          80.8       99.4          77.2        100.0         91.1
35          95.3       93.4         100.0         62.5         84.2

    Average_Score Pass_Status
10         95.625        Pass
61         95.200        Pass
8          92.125        Pass
16         89.350        Pass
35         87.800        Pass
Department with highest avg score: 0     83.57500
2     73.40000
3     54.47500
5     59.20000
18    64.72500
19    55.32500
31    53.84359
Name: Average_Score, dtype: float64
Average attendance by dept Department
 Data Science       76.700000
Commerce            77.437500
Computer Science    82.768025
Computer science    92.100000
Data Science        82.076768
Electronics         80.576923
data science        81.672727
Name: Attendance, dtype: float64
No. of students who passed and failed Pass_Status
Fail     8
Pass    72
Name: Student_ID, dtype: int64
Summary:
              Age  Attendance  Python_Score   SQL_Score  Pandas_Score  \
count  80.000000   80.000000     80.000000   80.000000     80.000000
mean   22.012987   81.672727     72.821795   70.445000     70.365385
std     2.113809    9.861453     16.509074   14.630417     15.612830
min    19.000000   56.300000     39.500000   38.300000     25.000000
25%    20.000000   76.175000     64.575000   60.650000     61.800000
50%    22.000000   81.536364     72.100000   69.300000     70.182692
75%    24.000000   86.400000     85.775000   81.150000     82.125000
max    25.000000  100.000000    100.000000  100.000000    100.000000

       NumPy_Score  Final_Score  Average_Score
count    80.000000    80.000000      80.000000
mean     68.574359    70.696154      70.551635
std      16.208096    13.874833      13.402582
min      25.000000    40.600000      36.625000
25%      57.325000    60.750000      62.525000
50%      69.487179    70.850000      70.900000
75%      80.550000    82.025000      82.262500
max     100.000000    97.000000      95.625000

Q17. Sales Data Analysis

In [ ]:
# A. DATA PREPARATION
import numpy as np
import pandas as pd

# Load the CSV file
sales = pd.read_csv("/content/drive/MyDrive/DSA/Assessment 2/sales.csv")

# Convert Order_Date to Pandas datetime type
sales['Order_Date'] = pd.to_datetime(sales['Order_Date'])

# Check for missing values
missing= student.isnull().sum()
print(missing)